# Site Info
title:              "Ten Second Thought"
description:        "Tinking..."

# Google APIs
google_verify:      epFgX0s_0RM3CdjwFcsewfXzPov2g8s9ZBOLyaIUH-o # Your Google Verification - set to 'false' to disable
google_analytics:   UA-XXXXXXX-X # Your Google Analytics code - set to 'false' to disable

# Author Info
author_name:        "DS" # Your name here
author_email:       10st@live.com # Your email here
author_gravatar:    b2b429dd81d366b42a74a36f8e237286 # Your Gravatar md5 hash here for logo

twitter_username:   HeiswayiNrird # set to 'false' to disable
github_username:    heiswayi # set to 'false' to disable


# Site Settings
url:                https://tensecondthought.com # main url can chnge nce other one activates
baseurl:            / # for gh-pages
permalink:          /posts/:title # Post permalink
timezone:           Pacific/Auckland # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to false to disable


# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
